services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres 
      DB_PASS: postgres
      REDIS_HOST: redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    command: >
      sh -c "npx typeorm-ts-node-commonjs migration:run -d ./ormconfig.ts && exec yarn start"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
      - app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      REDIS_HOST: redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    command: yarn run worker

volumes:
  postgres_data:
